POST http://localhost:5000/private/placeorder HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTdlY2I5NjBlY2IxMGZjY2RlMzQwZSIsImlhdCI6MTYyNTgxMjE1MywiZXhwIjoxNjI4NDA0MTUzLCJpc3MiOiJsb2NhbGhvc3QuY29tIiwianRpIjoiMTYyNTgxMjE1MzkzOC0yMTcxNjhlZDEyY2RiNGExZWQzZWI5MjMifQ.BTLHdTntlwL8VRzaJzjeVl7Vw6v2DUOCsWavjXn8uXc
Content-Type: application/json

{
    "items": [
        {
            "_id": "60c34ee5b4a84026f89d3878",
            "qty": 1
        },
        {
            "_id":"60d974c18e545e0ad81ebc11",
            "qty": 2
        }
    ]
}

### fetch userorders
GET http://localhost:5000/private/fetchuserorders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTdlY2I5NjBlY2IxMGZjY2RlMzQwZSIsImlhdCI6MTYyNTgxMjE1MywiZXhwIjoxNjI4NDA0MTUzLCJpc3MiOiJsb2NhbGhvc3QuY29tIiwianRpIjoiMTYyNTgxMjE1MzkzOC0yMTcxNjhlZDEyY2RiNGExZWQzZWI5MjMifQ.BTLHdTntlwL8VRzaJzjeVl7Vw6v2DUOCsWavjXn8uXc

### private test
GET http://localhost:5000/private/privatetest HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTdlY2I5NjBlY2IxMGZjY2RlMzQwZSIsImlhdCI6MTYyNTgxMjE1MywiZXhwIjoxNjI4NDA0MTUzLCJpc3MiOiJsb2NhbGhvc3QuY29tIiwianRpIjoiMTYyNTgxMjE1MzkzOC0yMTcxNjhlZDEyY2RiNGExZWQzZWI5MjMifQ.BTLHdTntlwL8VRzaJzjeVl7Vw6v2DUOCsWavjXn8uXc