### most popular
GET http://localhost:5000/public/mostpopular?limit=2 HTTP/1.1

### search by name
GET http://localhost:5000/public/productname/cake  HTTP/1.1

### fetch single product by given id  
GET http://localhost:5000/public/productid/60c34d8db4a84026f89d3876  HTTP/1.1

### fetch New products based on =>  pagination-limit || pagination-categories-limit ||  limit || categories || categories-limit
GET http://localhost:5000/public/products?page=1&categories=cake&limit=10 HTTP/1.1

### images
GET http://localhost:5000/public/images/ HTTP/1.1

### /alldistinctcategories
GET http://localhost:5000/public/alldistinctcategories?fav=t HTTP/1.1

### /search by cat or Fav
GET http://localhost:5000/public/catandflav?categories=cake&flavors=chocolate HTTP/1.1
